parameters:
- name: enabled
  type: boolean
  default: true
- name: stageName
  type: string
  default: ''
- name: stageDependencies 
  type: object 
  default: 


stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}
    # condition: 
    dependsOn: ${{ parameters.stageDependencies }}
    # pool:
    jobs:
    - job: SCAScanning
      displayName: SCA Scanning
      steps:
      # - bash: |
      #     echo 'SCA Scanning...'
      #   displayName: SCA Scanning
      - task: dependency-check-build-task@6
        inputs:
          projectName: 'freddieentity'
          scanPath: '$(System.DefaultWorkingDirectory)'
          format: 'HTML'
          reportsDirectory: '$(System.DefaultWorkingDirectory)/Reports'
          reportFilename: 'dependencyCheckReport.html'