parameters:
- name: environment
  type: string
  default: dev
- name: stageName
  type: string
  default: 
- name: stageDependencies 
  type: object 
  default: []


stages:
  - stage:
    displayName: ${{ parameters.stageName }}
    # condition: 
    dependsOn: ${{ parameters.stageDependencies }}
    # pool:
    jobs:
    - job: SCAScanning
      displayName: SCA Scanning
      steps:
      - bash: |
          echo 'SCA Scanning...'
        displayName: SCA Scanning