parameters:
- name: environment
  type: string
  default: dev
- name: enabled
  type: boolean
  default: true
- name: stageName
  type: string
  default: ''
- name: stageDependencies 
  type: object 
  default: 


stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}
    # condition: 
    dependsOn: ${{ parameters.stageDependencies }}
    # pool:
    jobs:
    - job: HelmPackage
      displayName: HelmPackage
      steps:
        - task: HelmDeploy@0
        inputs:
            command: package
            chartPath: $(chartPath)
            chartVersion: $(Build.SourceBranchName)
            arguments: '--app-version $(Build.SourceBranchName)'

        - task: AzureCLI@1
        inputs:
            azureSubscription: $(AzureSubscription)
            scriptLocation: inlineScript
            inlineScript: |
            az acr helm push $(System.ArtifactsDirectory)/$(repositoryName)-$(Build.SourceBranchName).tgz --name $(AzureContainerRegistry);