# Get Secrets
# Lint
# Restore
# Build
# Unit tests
# Integration tests
# Publish build artifacts
# Publish container image
stages:
  # UnitTest
  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/test/unit-test.yaml
    parameters:
      enabled: ${{ parameters.enableUnitTest }}
      stageName: UnitTest
      stageDependencies: 

  # SCA
  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/security/sca/owasp-dependency-check.yaml
    parameters:
      enabled: ${{ parameters.enableSCA }}
      stageName: SCA
      stageDependencies:
        - UnitTest

  # SAST
  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/security/sast/sonarqube.yaml
    parameters:
      enabled: ${{ parameters.enableSAST }}
      stageName: SAST
      stageDependencies:
        - UnitTest
      sonarQubeToken: 4ae523f01ada58d6b50e1667024d06494989a1c9
      sonarQubeOrganization: freddieentity
      sonarQubeProjectKey: complete-cicd
      sonarQubeSources: $(Pipeline.Workspace)
      sonarQubeHostURL: https://sonarcloud.io

  # Build
  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/build/container-image-build.yaml
    parameters:
      enabled: ${{ parameters.enableBuild }}
      stageName: Build
      stageDependencies:
        - SCA
        - SAST
      containerRegistryName: ${{ parameters.containerRegistryName }}
      containerImageName: ${{ parameters.containerImageName }}
      containerImageTag: ${{ parameters.containerImageTag }}
      helmRemoteChartRepositoryURL: https://freddieentity.github.io/universal-helm-charts
      helmRemoteChartRepositoryName: universal-helm-charts
      helmChartPath: $(System.DefaultWorkingDirectory)/deploy/helm
      helmChartName: 
      helmChartVersion: 

  # Container Image Scan
  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/security/container/trivy.yaml
    parameters:
      enabled: ${{ parameters.enableContainerImageScan }}
      stageName: ContainerImageScan
      stageDependencies:
        - Build
      trivyTemplatePath: /templates/security/container/trivy.tpl
      containerRegistryName: ${{ parameters.containerRegistryName }}
      containerImageName: ${{ parameters.containerImageName }}
      containerImageTag: ${{ parameters.containerImageTag }}

  # Preview Deployment
  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/deploy/basic.yaml
    parameters:
      environment: Development
      enabled: ${{ parameters.enablePreviewDeployment }}
      stageName: Development
      stageDependencies:
        - Build
      deploymentPoolName: Homelabpool


parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Development
  # - name: unitTestSourcesDirectory
  #   displayName: Unit Test Sources Directory
  #   type: string
  #   default: ''
  # - name: projectSourcesDirectory
  #   displayName: Project Sources Directory
  #   type: string
  #   default: ''
  - name: containerRegistryName
    type: string
    default: freddieentity.azurecr.io
  - name: containerImageName
    type: string
    default: weatherservice
  - name: containerImageTag
    type: string
    default: $(Build.BuildNumber)
  - name: enableUnitTest
    type: boolean
    default: true
  - name: enableSCA
    type: boolean
    default: true
  - name: enableSAST
    type: boolean
    default: true
  - name: enableBuild
    type: boolean
    default: true
  - name: enableContainerImageScan
    type: boolean
    default: true
  - name: enablePreviewDeployment
    type: boolean
    default: true