parameters:
  - name: agentName
    type: string
  - name: secretEngine
    type: string
    values:
      - kv
      - azure
      - pki
  - name: secretPath
    type: string

jobs:
  - job: get_secrets
    displayName: "Get Secrets"
    pool:
      name: ${{ parameters.agentName }}
    steps:
    - bash: |
        echo ''
        echo '===== HASHICORP VAULT ====='
        curl \
          -H "X-Vault-Token: $VAULT_TOKEN" \
          -X GET \
          http://127.0.0.1:8200/v1/secret/data/${{ parameters.secretPath }} | jq .data.data > "$(Agent.TempDirectory)/$(Build.BuildNumber)secrets.json"
      displayName: Get Hashicorp Vault Secrets
    - bash: |
        echo ''