parameters:
- name: enabled
  type: boolean
  default: true
- name: stageDependencies 
  type: object 
  default: 
- name: stageName
  type: string
- name: trivyTemplatePath
  type: string
  default: 'https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/junit.tpl'
- name: containerRegistryName
  type: string
- name: containerImageName
  type: string
- name: containerImageTag
  type: string

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}
    # condition: 
    dependsOn: ${{ parameters.stageDependencies }}
    # pool:
    jobs:
    - job: TrivyContainerImageScanning
      displayName: Trivy Container Image Scanning
      steps:
      - bash: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy  
        displayName: Trivy Installation
      
      - bash: |
          trivy image --severity LOW,MEDIUM,HIGH,CRITICAL --format template --template @${{ parameters.trivyTemplatePath }} -o junit-trivy.xml ${{ parameters.containerRegistryName }}/${{ parameters.containerImageName }}:${{ parameters.containerImageTag }}         
        displayName: Trivy Container Image Scanning

      # - task: PublishBuildArtifacts@1
      #   displayName: Trivy Publish Artifact Staging Directory
      #   inputs:
      #     pathToPublish: '$(Build.ArtifactStagingDirectory)'
      #     artifactName: 'Trivy'
      #     publishLocation: 'Container'

      # - task: DownloadBuildArtifacts@0
      #   inputs:
      #     buildType: 'current'
      #     downloadType: 'single'
      #     downloadPath: '$(System.ArtifactsDirectory)'
      #     artifactName: 'Trivy'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/junit*.xml'
          mergeTestResults: true
          failTaskOnFailedTests: false
          testRunTitle: 'Trivy Vulnerabilities Report'
        condition: 'always()'
        displayName: Trivy Report Visualization