version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.0
    volumes:
      - ./loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:latest
    container_name: fluent-bit
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit/:/fluent-bit/etc/
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    user: "1000"
    volumes:
    - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000" #you might need to change this
    restart: unless-stopped
    networks:
      - loki
  app:
    image: kodekloud/event-simulator
    container_name: event-simulator
    ports:
      - "4000:3000"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224