parameters:
- name: environment
  type: string
  default: dev
- name: stageName
  type: string
  default: ''
- name: stageDependencies 
  type: object 
  default: 
- name: targetEndpoint
  type: string
- name: reportOutputPath
  type: string
  default: $(Build.ArtifactStagingDirectory)

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}
    # condition: 
    dependsOn: ${{ parameters.stageDependencies }}
    # pool:
    jobs:
    - job: ZAPDASTScanning
      displayName: ZAP DAST Scanning
      steps:
      - script: |
            wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Linux.tar.gz
            mkdir zap
            tar -xvf ZAP_2.11.1_Linux.tar.gz
            cd ZAP_2.11.1
            ./zap.sh -cmd -quickurl ${{ parameters.targetEndpoint }} -quickprogress -quickout ${{ parameters.reportOutputPath }}
        displayName: ZAP Installation and Scanning

      - task: PublishBuildArtifacts@1
        displayName: Zap Report Export
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: zap_report.html