# Deploy to staging
# Acceptance tests
# Promote container image
# Manual intervention (optional)
# Release
trigger: none
resources:
  # https://learn.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-containers
  pipelines: # https://bartwullems.blogspot.com/2021/06/azure-pipelines-template-expression-is.html
  - pipeline: onlineboutique-weatherservice # Can't use template expression for resources section except for containers
    source: onlineboutique-weatherservice
    trigger:
      branches:
        include: [ refs/heads/main, refs/heads/develop, refs/heads/release/* ]


# https://adamtheautomator.com/azure-devops-variables/
# https://stackoverflow.com/questions/65598404/need-replace-alias-value-of-predefined-variables-in-azure-devops-pipelines
variables: # https://tsuyoshiushio.medium.com/how-to-pass-variables-with-pipeline-trigger-in-azure-pipeline-5771c5f18f91
  - template: ${{variables['System.DefaultWorkingDirectory']}}/variables/common/global.yaml

stages: # https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/deployment-strategies.md
  # Development
  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/deploy/aks.yaml
    parameters:
      environment: Development
      stageName: Development
      deploymentPoolName: Homelabpool
      azureServiceConnection: SC ARM
      containerRegistryName: $(CONTAINER_REGISTRY_NAME)
      resourceGroup: ${{ parameters.resourceGroup }}
      kubernetesCluster: ${{ parameters.kubernetesCluster }}
      kubernetesNamespace: ${{ parameters.kubernetesNamespace }}
      containerImageName: ${{ parameters.containerImageName }}
      containerImageTag: ${{ parameters.containerImageTag }}

  # # Test
  # - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/deploy/basic.yaml
  #   parameters:
  #     environment: Test
  #     stageName: Test
  #     stageDependencies:
  #       - Development
  #     deploymentPoolName: Homelabpool
  #     microserviceName: weatherservice

  # # Automation Test
  # - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/test/automation-test.yaml
  #   parameters:
  #     stageName: AutomationTest
  #     stageDependencies:
  #       - Test

  # # DAST
  # - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/security/dast/owasp-zap.yaml
  #   parameters:
  #     stageName: DAST
  #     stageDependencies:
  #       - Test
  #     targetEndpoint: https://www.example.com
  #     reportOutputPath: /home/vsts/work/1/a/zap_report.html
        
  # # Staging   
  # - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/deploy/basic.yaml
  #   parameters:
  #     environment: Staging
  #     stageName: Staging
  #     stageDependencies:
  #       - Test
  #     deploymentPoolName: Homelabpool
  #     microserviceName: weatherservice

  # # Production
  # - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/deploy/basic.yaml
  #   parameters:
  #     environment: Production
  #     stageName: Production
  #     stageDependencies:
  #       - Staging
  #     deploymentPoolName: Homelabpool
  #     microserviceName: weatherservice


parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Development
  - name: resourceGroup
    type: string
    default: "rg-homelab-online-boutique"
  - name: kubernetesCluster
    type: string
    default: "aks-homelab-online-boutique"
  - name: kubernetesNamespace
    type: string
    default: "develop"
  - name: containerImageName
    type: string
    default: "nginx"
  - name: containerImageTag
    type: string
    default: "develop"